# Generated by Django 2.2.1 on 2019-06-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_machine', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Machine Service Models',
            },
        ),
        migrations.CreateModel(
            name='RegisterPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.IntegerField()),
                ('position', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('chanel', models.IntegerField()),
                ('task', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_register', to='service.MachineService')),
            ],
            options={
                'verbose_name_plural': 'Register Photo Models',
            },
        ),
    ]
